#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Robin Mitra <robinmitra1@gmail.com>
#

##########
# Custom #
##########

source "${HOME}/.aliases.sh"
source "${HOME}/.functions.sh"
source "${HOME}/.key-bindings.sh"

# Optional work-specific stuff.
if [[ -s "${HOME}/.work.sh" ]]; then
  source "${HOME}/.work.sh"
fi

##########
# Prezto #
##########

# Initialise Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#######
# FZF #
#######

# Initialise FZF.
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Use 'fd' as the default source for FZF. Note that 'fd' doesn't include hidden and ignored files, by default.
# export FZF_DEFAULT_COMMAND='fd --type f' # Use this to exclude hidden and ignored files.
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --no-ignore --exclude .git' # Use this alternative to include hidden files and only exclude '.git' directory.
#export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --no-ignore' # Use this alternative to include everything.

# Use 'fd' for Ctrl+t as well.
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Show a tree view on the right of entry selected, when using Esc+c.
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'" 

# Show a tree view on the right of entry selected, when using Ctrl+t.
export FZF_CTRL_T_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"

# Show a preview of command (useful for viewing longer commands going beyond the screen) when '?' is pressed, when using Ctrl+r.
export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"

#######
# GRC #
#######

# Add gcloud to $PATH.
[[ -s "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc" ]] && source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc
# Shell command completion.
[[ -s "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc" ]] && source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc

#######
# GRC #
#######

[[ -s "/usr/local/etc/grc.zsh" ]] && source /usr/local/etc/grc.zsh

#############
# Languages #
#############

# Ruby
eval "$(rbenv init -)"

# Node.js
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

# Go
[[ -s "/Users/robinmitra/.gvm/scripts/gvm" ]] && source "/Users/robinmitra/.gvm/scripts/gvm"

# Python
eval "$(pyenv init -)"

# Flutter
eval "$(pyenv init -)"

##########
# Others #
##########

eval $(thefuck --alias)

source /usr/local/opt/git-extras/share/git-extras/git-extras-completion.zsh

# Tells `pinentry`, the software GPG uses for entering passcode, where to prompt for passcode.
# This will allow signing commits from command line Git.
export GPG_TTY=$(tty)
